/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    colours: Colour;
    products: Product;
    pages: Page;
    documents: Document;
    carts: Cart;
    orders: Order;
    payments: Payment;
    leads: Lead;
    redirects: Redirect;
    'import-batches': ImportBatch;
    'import-warnings': ImportWarning;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    colours: ColoursSelect<false> | ColoursSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    carts: CartsSelect<false> | CartsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    payments: PaymentsSelect<false> | PaymentsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'import-batches': ImportBatchesSelect<false> | ImportBatchesSelect<true>;
    'import-warnings': ImportWarningsSelect<false> | ImportWarningsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('uk' | 'en' | 'pl') | ('uk' | 'en' | 'pl')[];
  globals: {};
  globalsSelect: {};
  locale: 'uk' | 'en' | 'pl';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'superAdmin' | 'owner' | 'contentManager' | 'productManager' | 'salesManager' | 'translator' | 'viewer';
  /**
   * Вимкніть замість видалення, щоб зберегти історію дій користувача.
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Обов'язково для фото товарів/сторінок. Залиште порожнім лише для суто декоративних зображень.
   */
  alt?: string | null;
  /**
   * «Технічне креслення» — для габаритних креслень і розрізів. Такі файли показуються в галереї окремо й ніколи не стають головним фото товару.
   */
  kind: 'photo' | 'drawing';
  caption?: string | null;
  /**
   * Фотограф / проєкт / джерело, якщо застосовно.
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * Використовується в URL, напр. sinks, planters.
   */
  slug: string;
  /**
   * Залиште порожнім для категорії верхнього рівня.
   */
  parent?: (number | null) | Category;
  sortOrder?: number | null;
  showInMenu?: boolean | null;
  /**
   * Старий URL з Horoshop, якщо потрібен редирект.
   */
  oldUrl?: string | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  /**
   * Заповнюється автоматично імпортером Horoshop. Не редагувати вручну.
   */
  legacy?: {
    legacySource?: 'horoshop' | null;
    legacyId?: string | null;
    legacyUrl?: string | null;
    legacySlug?: string | null;
    importedAt?: string | null;
    importBatchId?: (number | null) | ImportBatch;
    migrationStatus?: ('pending' | 'imported' | 'updated' | 'skipped' | 'conflict' | 'failed') | null;
    migrationWarnings?:
      | {
          warning: string;
          id?: string | null;
        }[]
      | null;
    sourceChecksum?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "import-batches".
 */
export interface ImportBatch {
  id: number;
  source: 'horoshop';
  mode: 'dryRun' | 'live';
  status: 'running' | 'completed' | 'failed';
  startedAt: string;
  finishedAt?: string | null;
  totals?: {
    createdCount?: number | null;
    updatedCount?: number | null;
    skippedCount?: number | null;
    conflictCount?: number | null;
    failedCount?: number | null;
  };
  triggeredBy?: (number | null) | User;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "colours".
 */
export interface Colour {
  id: number;
  displayName: string;
  slug: string;
  /**
   * Екранне наближення кольору, напр. #A6A6A6. Не гарантія збігу пігменту — див. disclaimer.
   */
  digitalPreviewHex: string;
  /**
   * Реальне фото застиглого/тонованого зразка.
   */
  textureImage?: (number | null) | Media;
  /**
   * Лише якщо підтверджено з майстернею — інакше залиште порожнім.
   */
  ralOrNcsReference?: string | null;
  textMode: 'dark' | 'light';
  availableCategories?: (number | Category)[] | null;
  physicalSampleAvailable?: boolean | null;
  /**
   * Доплата за колір (UAH), якщо є. Залиште порожнім, якщо доплати немає.
   */
  surcharge?: number | null;
  disclaimer: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  slug: string;
  sku: string;
  category: number | Category;
  availableColours?: (number | Colour)[] | null;
  mainImage?: (number | null) | Media;
  gallery?: (number | Media)[] | null;
  /**
   * Технічні файли товару (PDF/DWG/DXF/SKP/OBJ/STL/BIM) — окремо від фото в gallery.
   */
  documents?: (number | Document)[] | null;
  shortDescription?: string | null;
  editorialStatus: 'draft' | 'readyForReview' | 'published' | 'scheduled' | 'archived' | 'discontinued';
  stockStatus: 'inStock' | 'madeToOrder' | 'availableForOrder' | 'quoteOnly' | 'unavailable';
  /**
   * Структуровані характеристики. Реальні значення на сьогодні підтверджені лише для мийок (Матеріал/Висота/Діаметр/Вага/Тип змішувача/Підключення) — інші категорії поки без структурованих даних на сайті, тому всі поля тут необов'язкові й заповнюються по мірі появи підтверджених даних.
   */
  specs?: {
    material?: string | null;
    technology?: string | null;
    reinforcement?: string | null;
    coating?: string | null;
    usage?: ('indoor' | 'outdoor')[] | null;
    width?: {
      value?: number | null;
      unit?: ('mm' | 'cm' | 'm') | null;
    };
    depth?: {
      value?: number | null;
      unit?: ('mm' | 'cm' | 'm') | null;
    };
    height?: {
      value?: number | null;
      unit?: ('mm' | 'cm' | 'm') | null;
    };
    diameter?: {
      value?: number | null;
      unit?: ('mm' | 'cm' | 'm') | null;
    };
    thickness?: {
      value?: number | null;
      unit?: ('mm' | 'cm' | 'm') | null;
    };
    weight?: {
      value?: number | null;
      unit?: 'kg' | null;
    };
    weightPerArea?: {
      value?: number | null;
      unit?: 'kg/m2' | null;
    };
    drainDiameter?: {
      value?: number | null;
      unit?: ('mm' | 'cm' | 'm') | null;
    };
    coverageArea?: {
      value?: number | null;
      unit?: 'm2' | null;
    };
    piecesPerPack?: {
      value?: number | null;
      unit?: 'pcs' | null;
    };
    /**
     * Напр. накладна, врізна, підстільна.
     */
    mountType?: string | null;
    faucetType?: string | null;
    /**
     * Наявність/розташування отвору під змішувач.
     */
    faucetHole?: string | null;
    /**
     * Наявність переливу.
     */
    overflow?: string | null;
    wallConnection?: string | null;
    floorConnection?: string | null;
    /**
     * Загальний опис підключення, як він поданий у джерелі (напр. «можливе зі стіни або з підлоги»). Використовуйте окремі поля вище лише коли підключення зі стіни й з підлоги описані різними, підтвердженими фактами.
     */
    connection?: string | null;
    drainage?: string | null;
    fixingMethod?: string | null;
    packagingType?: string | null;
    warranty?: string | null;
    care?: string | null;
    countryOfOrigin?: string | null;
  };
  /**
   * Базова ціна, UAH. Залиште порожнім для товарів "лише за запитом ціни".
   */
  basePrice?: number | null;
  /**
   * Причина зміни ціни (напр. "перегляд собівартості матеріалу"). Записується в історію нижче при збереженні; саме поле не зберігається окремою колонкою в БД.
   */
  priceChangeReason?: string | null;
  /**
   * Заповнюється автоматично при зміні базової ціни. Не редагується вручну.
   */
  priceHistory?:
    | {
        oldValue?: number | null;
        newValue?: number | null;
        changedBy?: (number | null) | User;
        changedAt?: string | null;
        reason?: string | null;
        id?: string | null;
      }[]
    | null;
  pricing?: {
    /**
     * Наразі лише UAH; мультивалютність — окрема майбутня фаза.
     */
    currency?: 'UAH' | null;
    /**
     * "Стара" ціна для показу знижки. Необов'язково.
     */
    compareAtPrice?: number | null;
    /**
     * Собівартість — приховано від Sales Manager/Перекладача/Перегляду, бачать лише ролі з доступом до редагування товарів.
     */
    costPrice?: number | null;
    vatState?: ('included' | 'excluded') | null;
    promoPrice?: number | null;
    promoStartDate?: string | null;
    promoEndDate?: string | null;
  };
  leadTimeDays?: {
    min?: number | null;
    max?: number | null;
    textOverride?: string | null;
    /**
     * Прискорений термін виготовлення за додаткову оплату, якщо доступний.
     */
    urgentLeadTimeDays?: number | null;
    productionCapacityStatus?: ('normal' | 'high' | 'paused') | null;
    /**
     * Тимчасове подовження терміну діє до цієї дати (напр. сезонне навантаження).
     */
    temporaryExtensionUntil?: string | null;
  };
  /**
   * Кожен рядок — конкретний варіант товару (SKU), що комбінує одну чи кілька осей опцій нижче. Порожні осі означають, що ця вісь не застосовна до цього варіанта.
   */
  variants?:
    | {
        sku: string;
        optionAxes?: {
          colour?: (number | null) | Colour;
          size?: string | null;
          material?: string | null;
          coating?: string | null;
          mount?: string | null;
          faucetType?: string | null;
          hole?: string | null;
          overflow?: string | null;
          connection?: string | null;
          kit?: string | null;
          /**
           * Довільна вісь, якщо жодна з вище не підходить.
           */
          custom?: string | null;
        };
        price?: number | null;
        status?: ('inStock' | 'madeToOrder' | 'availableForOrder' | 'quoteOnly' | 'unavailable') | null;
        leadTimeOverride?: string | null;
        stockNote?: string | null;
        photos?: (number | Media)[] | null;
        documents?: (number | Document)[] | null;
        /**
         * Ідентифікатор варіанта в Shopify, якщо/коли підключиться синхронізація.
         */
        shopifyId?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Старий URL з Horoshop, якщо потрібен редирект.
   */
  oldUrl?: string | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    focusKeyword?: string | null;
    ogImage?: (number | null) | Media;
    canonicalUrl?: string | null;
    noIndex?: boolean | null;
    oldUrls?:
      | {
          url: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Заповнюється автоматично імпортером Horoshop. Не редагувати вручну.
   */
  legacy?: {
    legacySource?: 'horoshop' | null;
    legacyId?: string | null;
    legacyUrl?: string | null;
    legacySlug?: string | null;
    importedAt?: string | null;
    importBatchId?: (number | null) | ImportBatch;
    migrationStatus?: ('pending' | 'imported' | 'updated' | 'skipped' | 'conflict' | 'failed') | null;
    migrationWarnings?:
      | {
          warning: string;
          id?: string | null;
        }[]
      | null;
    sourceChecksum?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  name: string;
  format:
    | 'pdf'
    | 'dwg'
    | 'dxf'
    | 'skp'
    | 'obj'
    | 'stl'
    | 'bim'
    | 'installInstructions'
    | 'careInstructions'
    | 'warranty'
    | 'spec'
    | 'dimensionalDrawing';
  language?: ('uk' | 'en' | 'pl') | null;
  version?: string | null;
  documentDate?: string | null;
  visibility: 'public' | 'private' | 'designerOnly';
  linkedProduct?: (number | null) | Product;
  /**
   * SKU варіанта, якщо документ стосується конкретного варіанта, а не всього товару.
   */
  linkedVariantSku?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Напр. about, colours, contact — без початкового /.
   */
  slug: string;
  status: 'draft' | 'review' | 'scheduled' | 'published' | 'archived';
  /**
   * Для запланованої публікації.
   */
  publishAt?: string | null;
  blocks?:
    | (
        | {
            /**
             * Лише для адмінки — не показується на сайті.
             */
            internalLabel?: string | null;
            hideOnMobile?: boolean | null;
            hideOnDesktop?: boolean | null;
            heading: string;
            subheading?: string | null;
            image?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            /**
             * Лише для адмінки — не показується на сайті.
             */
            internalLabel?: string | null;
            hideOnMobile?: boolean | null;
            hideOnDesktop?: boolean | null;
            content: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            /**
             * Лише для адмінки — не показується на сайті.
             */
            internalLabel?: string | null;
            hideOnMobile?: boolean | null;
            hideOnDesktop?: boolean | null;
            size?: ('sm' | 'md' | 'lg' | 'xl') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'spacer';
          }
      )[]
    | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts".
 */
export interface Cart {
  id: number;
  sessionToken: string;
  currency: 'UAH';
  lines?:
    | {
        productId?: (number | null) | Product;
        /**
         * Raw domain ProductId string (a slug in horoshop-snapshot bridge mode) — always populated, unlike the best-effort `productId` relationship above.
         */
        productRef: string;
        /**
         * SKU варіанта в масиві `variants` товару — окремої колекції варіантів немає.
         */
        variantSku: string;
        sku: string;
        name: {
          uk: string;
          en?: string | null;
          pl?: string | null;
        };
        mediaId?: (number | null) | Media;
        quantity: number;
        unitPrice: {
          currency?: 'UAH' | null;
          minorUnits: number;
        };
        options?:
          | {
              optionKey:
                | 'colour'
                | 'size'
                | 'material'
                | 'coating'
                | 'mount'
                | 'faucetType'
                | 'hole'
                | 'overflow'
                | 'connection'
                | 'kit'
                | 'custom';
              value: string;
              label: {
                uk: string;
                en?: string | null;
                pl?: string | null;
              };
              id?: string | null;
            }[]
          | null;
        addedAt: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Для фонового очищення покинутих кошиків. Необов'язково.
   */
  expiresAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  orderNumber: string;
  lines?:
    | {
        productId?: (number | null) | Product;
        /**
         * Raw domain ProductId string (a slug in horoshop-snapshot bridge mode) — always populated, unlike the best-effort `productId` relationship above.
         */
        productRef: string;
        variantSku: string;
        sku: string;
        name: {
          uk: string;
          en?: string | null;
          pl?: string | null;
        };
        mediaId?: (number | null) | Media;
        quantity: number;
        unitPriceMinorUnits: number;
        lineTotalMinorUnits: number;
        options?:
          | {
              optionKey:
                | 'colour'
                | 'size'
                | 'material'
                | 'coating'
                | 'mount'
                | 'faucetType'
                | 'hole'
                | 'overflow'
                | 'connection'
                | 'kit'
                | 'custom';
              value: string;
              label: {
                uk: string;
                en?: string | null;
                pl?: string | null;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  currency: 'UAH';
  totals: {
    subtotalMinorUnits: number;
    discountTotalMinorUnits: number;
    deliveryTotalMinorUnits: number;
    totalMinorUnits: number;
  };
  deliveryMethod: {
    type: 'novaPoshtaBranch' | 'novaPoshtaCourier' | 'courier' | 'pickup';
    cityName?: string | null;
    branchNumber?: string | null;
    branchAddress?: string | null;
    address?: string | null;
    /**
     * Немає окремої колекції `Stockists` ще — вкажіть точку самовивозу текстом до появи такої колекції.
     */
    stockistNote?: string | null;
  };
  customer: {
    fullName: string;
    phone: string;
    email?: string | null;
    companyName?: string | null;
    notes?: string | null;
  };
  status:
    | 'pending'
    | 'awaitingPayment'
    | 'paid'
    | 'processing'
    | 'shipped'
    | 'completed'
    | 'cancelled'
    | 'refunded'
    | 'failed';
  paymentId?: (number | null) | Payment;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments".
 */
export interface Payment {
  id: number;
  orderId: number | Order;
  provider: 'liqpay' | 'manual';
  amount: {
    currency?: 'UAH' | null;
    minorUnits: number;
  };
  status: 'pending' | 'success' | 'failure' | 'reversed' | 'sandbox';
  /**
   * LiqPay-транзакції id — використовується для ідемпотентності callback-обробника.
   */
  externalId?: string | null;
  signatureVerified?: boolean | null;
  /**
   * Опаковий запис для аудиту/спорів. Ніколи не містить даних картки.
   */
  rawCallbackPayload?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  type: 'contact' | 'callback' | 'quote' | 'designer' | 'warranty' | 'sample';
  status: 'new' | 'inProgress' | 'waitingForCustomer' | 'quoted' | 'won' | 'lost' | 'spam' | 'closed';
  locale: 'uk' | 'en' | 'pl';
  /**
   * Шлях сторінки, з якої надіслано форму (без query-параметрів, щоб не зберігати PII з трекінгу).
   */
  sourcePath?: string | null;
  name: string;
  phone: string;
  /**
   * Обов'язково лише для типу «designer» — валідується на сервері (Zod), не тут.
   */
  email?: string | null;
  message?: string | null;
  preferredTime?: string | null;
  productId?: (number | null) | Product;
  variantSku?: string | null;
  quantity?: number | null;
  companyName?: string | null;
  portfolioUrl?: string | null;
  orderNumber?: string | null;
  issueDescription?: string | null;
  photoIds?: (number | Media)[] | null;
  address?: string | null;
  productIds?: (number | Product)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  fromPath: string;
  toPath: string;
  statusCode: '301' | '302';
  note?: string | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "import-warnings".
 */
export interface ImportWarning {
  id: number;
  importBatch: number | ImportBatch;
  entityType:
    | 'product'
    | 'category'
    | 'colour'
    | 'material'
    | 'page'
    | 'article'
    | 'project'
    | 'faqItem'
    | 'stockist'
    | 'resource'
    | 'navigationItem';
  legacyId: string;
  severity: 'warning' | 'error';
  message: string;
  resolved?: boolean | null;
  resolutionNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'colours';
        value: number | Colour;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'carts';
        value: number | Cart;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'payments';
        value: number | Payment;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'import-batches';
        value: number | ImportBatch;
      } | null)
    | ({
        relationTo: 'import-warnings';
        value: number | ImportWarning;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  kind?: T;
  caption?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  parent?: T;
  sortOrder?: T;
  showInMenu?: T;
  oldUrl?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  legacy?:
    | T
    | {
        legacySource?: T;
        legacyId?: T;
        legacyUrl?: T;
        legacySlug?: T;
        importedAt?: T;
        importBatchId?: T;
        migrationStatus?: T;
        migrationWarnings?:
          | T
          | {
              warning?: T;
              id?: T;
            };
        sourceChecksum?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "colours_select".
 */
export interface ColoursSelect<T extends boolean = true> {
  displayName?: T;
  slug?: T;
  digitalPreviewHex?: T;
  textureImage?: T;
  ralOrNcsReference?: T;
  textMode?: T;
  availableCategories?: T;
  physicalSampleAvailable?: T;
  surcharge?: T;
  disclaimer?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  sku?: T;
  category?: T;
  availableColours?: T;
  mainImage?: T;
  gallery?: T;
  documents?: T;
  shortDescription?: T;
  editorialStatus?: T;
  stockStatus?: T;
  specs?:
    | T
    | {
        material?: T;
        technology?: T;
        reinforcement?: T;
        coating?: T;
        usage?: T;
        width?:
          | T
          | {
              value?: T;
              unit?: T;
            };
        depth?:
          | T
          | {
              value?: T;
              unit?: T;
            };
        height?:
          | T
          | {
              value?: T;
              unit?: T;
            };
        diameter?:
          | T
          | {
              value?: T;
              unit?: T;
            };
        thickness?:
          | T
          | {
              value?: T;
              unit?: T;
            };
        weight?:
          | T
          | {
              value?: T;
              unit?: T;
            };
        weightPerArea?:
          | T
          | {
              value?: T;
              unit?: T;
            };
        drainDiameter?:
          | T
          | {
              value?: T;
              unit?: T;
            };
        coverageArea?:
          | T
          | {
              value?: T;
              unit?: T;
            };
        piecesPerPack?:
          | T
          | {
              value?: T;
              unit?: T;
            };
        mountType?: T;
        faucetType?: T;
        faucetHole?: T;
        overflow?: T;
        wallConnection?: T;
        floorConnection?: T;
        connection?: T;
        drainage?: T;
        fixingMethod?: T;
        packagingType?: T;
        warranty?: T;
        care?: T;
        countryOfOrigin?: T;
      };
  basePrice?: T;
  priceChangeReason?: T;
  priceHistory?:
    | T
    | {
        oldValue?: T;
        newValue?: T;
        changedBy?: T;
        changedAt?: T;
        reason?: T;
        id?: T;
      };
  pricing?:
    | T
    | {
        currency?: T;
        compareAtPrice?: T;
        costPrice?: T;
        vatState?: T;
        promoPrice?: T;
        promoStartDate?: T;
        promoEndDate?: T;
      };
  leadTimeDays?:
    | T
    | {
        min?: T;
        max?: T;
        textOverride?: T;
        urgentLeadTimeDays?: T;
        productionCapacityStatus?: T;
        temporaryExtensionUntil?: T;
      };
  variants?:
    | T
    | {
        sku?: T;
        optionAxes?:
          | T
          | {
              colour?: T;
              size?: T;
              material?: T;
              coating?: T;
              mount?: T;
              faucetType?: T;
              hole?: T;
              overflow?: T;
              connection?: T;
              kit?: T;
              custom?: T;
            };
        price?: T;
        status?: T;
        leadTimeOverride?: T;
        stockNote?: T;
        photos?: T;
        documents?: T;
        shopifyId?: T;
        id?: T;
      };
  oldUrl?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        focusKeyword?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
        oldUrls?:
          | T
          | {
              url?: T;
              id?: T;
            };
      };
  legacy?:
    | T
    | {
        legacySource?: T;
        legacyId?: T;
        legacyUrl?: T;
        legacySlug?: T;
        importedAt?: T;
        importBatchId?: T;
        migrationStatus?: T;
        migrationWarnings?:
          | T
          | {
              warning?: T;
              id?: T;
            };
        sourceChecksum?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  publishAt?: T;
  blocks?:
    | T
    | {
        hero?:
          | T
          | {
              internalLabel?: T;
              hideOnMobile?: T;
              hideOnDesktop?: T;
              heading?: T;
              subheading?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              internalLabel?: T;
              hideOnMobile?: T;
              hideOnDesktop?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        spacer?:
          | T
          | {
              internalLabel?: T;
              hideOnMobile?: T;
              hideOnDesktop?: T;
              size?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  name?: T;
  format?: T;
  language?: T;
  version?: T;
  documentDate?: T;
  visibility?: T;
  linkedProduct?: T;
  linkedVariantSku?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts_select".
 */
export interface CartsSelect<T extends boolean = true> {
  sessionToken?: T;
  currency?: T;
  lines?:
    | T
    | {
        productId?: T;
        productRef?: T;
        variantSku?: T;
        sku?: T;
        name?:
          | T
          | {
              uk?: T;
              en?: T;
              pl?: T;
            };
        mediaId?: T;
        quantity?: T;
        unitPrice?:
          | T
          | {
              currency?: T;
              minorUnits?: T;
            };
        options?:
          | T
          | {
              optionKey?: T;
              value?: T;
              label?:
                | T
                | {
                    uk?: T;
                    en?: T;
                    pl?: T;
                  };
              id?: T;
            };
        addedAt?: T;
        id?: T;
      };
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  lines?:
    | T
    | {
        productId?: T;
        productRef?: T;
        variantSku?: T;
        sku?: T;
        name?:
          | T
          | {
              uk?: T;
              en?: T;
              pl?: T;
            };
        mediaId?: T;
        quantity?: T;
        unitPriceMinorUnits?: T;
        lineTotalMinorUnits?: T;
        options?:
          | T
          | {
              optionKey?: T;
              value?: T;
              label?:
                | T
                | {
                    uk?: T;
                    en?: T;
                    pl?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  currency?: T;
  totals?:
    | T
    | {
        subtotalMinorUnits?: T;
        discountTotalMinorUnits?: T;
        deliveryTotalMinorUnits?: T;
        totalMinorUnits?: T;
      };
  deliveryMethod?:
    | T
    | {
        type?: T;
        cityName?: T;
        branchNumber?: T;
        branchAddress?: T;
        address?: T;
        stockistNote?: T;
      };
  customer?:
    | T
    | {
        fullName?: T;
        phone?: T;
        email?: T;
        companyName?: T;
        notes?: T;
      };
  status?: T;
  paymentId?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments_select".
 */
export interface PaymentsSelect<T extends boolean = true> {
  orderId?: T;
  provider?: T;
  amount?:
    | T
    | {
        currency?: T;
        minorUnits?: T;
      };
  status?: T;
  externalId?: T;
  signatureVerified?: T;
  rawCallbackPayload?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  type?: T;
  status?: T;
  locale?: T;
  sourcePath?: T;
  name?: T;
  phone?: T;
  email?: T;
  message?: T;
  preferredTime?: T;
  productId?: T;
  variantSku?: T;
  quantity?: T;
  companyName?: T;
  portfolioUrl?: T;
  orderNumber?: T;
  issueDescription?: T;
  photoIds?: T;
  address?: T;
  productIds?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  fromPath?: T;
  toPath?: T;
  statusCode?: T;
  note?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "import-batches_select".
 */
export interface ImportBatchesSelect<T extends boolean = true> {
  source?: T;
  mode?: T;
  status?: T;
  startedAt?: T;
  finishedAt?: T;
  totals?:
    | T
    | {
        createdCount?: T;
        updatedCount?: T;
        skippedCount?: T;
        conflictCount?: T;
        failedCount?: T;
      };
  triggeredBy?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "import-warnings_select".
 */
export interface ImportWarningsSelect<T extends boolean = true> {
  importBatch?: T;
  entityType?: T;
  legacyId?: T;
  severity?: T;
  message?: T;
  resolved?: T;
  resolutionNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}